services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/hilthontt/warden-bot:latest
    container_name: warden-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - bot-data:/data
    stop_grace_period: 30s
    init: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot-data:
